// 1. Chỉ định nghĩa Hành động (Không kèm trạng thái)
export const LOG_ACTIONS = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  TAX_SUBMIT: 'TAX_SUBMIT',
  TAX_CLOSE_PERIOD: 'TAX_CLOSE_PERIOD',
  SET_ONBOARDING: 'SETUP_ONBOARDING',
  UPDATE_ONBOARDING: 'UPDATE_ONBOARDING',

  UPLOAD_IMG: 'UPLOAD_IMAGE_TO_CLOUDINARY',

  CREATE_INVOICE: 'CREATE_INVOICE',
  UPDATE_INVOICE: 'UPDATE_INVOICE',
  CANCEL_INVOICE: 'CANCEL_INVOICE',
  INVOICE_CQT_ISSUED: 'INVOICE_CQT_ISSUED',

  CREATE_INBOUND_INVOICE: 'CREATE_INBOUND_INVOICE',
  CANCEL_INBOUND_INVOICE: 'CANCEL_INBOUND_INVOICE',
  SYNC_INVENTORY: 'SYNC_INVENTORY',
  DELETE_INVOICE: 'DELETE_INVOICE',

  CREATE_VOUCHER_CATEGORY: 'CREATE_VOUCHER_CATEGORY',
  UPDATE_VOUCHER_CATEGORY: 'UPDATE_VOUCHER_CATEGORY',
  DELETE_VOUCHER_CATEGORY: 'DELETE_VOUCHER_CATEGORY',

  CREATE_VOUCHER: 'CREATE_VOUCHER',
  UPDATE_VOUCHER: 'UPDATE_VOUCHER',
  CANCEL_VOUCHER: 'CANCEL_VOUCHER',
  DELETE_VOUCHER: 'DELETE_VOUCHER',

  CREATE_PRODUCTION_ORDER: 'CREATE_PRODUCTION_ORDER',
  CANCEL_PRODUCTION_ORDER: 'CANCEL_PRODUCTION_ORDER',
  UPDATE_PRODUCTION_ORDER: 'UPDATE_PRODUCTION_ORDER',

  CREATE_FINANCIAL_PERIOD: 'CREATE_FINANCIAL_PERIOD',
  UPDATE_FINANCIAL_PERIOD: 'UPDATE_FINANCIAL_PERIOD',
  ENSURE_FINANCIAL_PERIOD: 'ENSURE_FINANCIAL_PERIOD',
  CLOSE_FINANCIAL_PERIOD: 'CLOSE_FINANCIAL_PERIOD',
  VALIDATE_FINANCIAL_PERIOD: 'VALIDATE_FINANCIAL_PERIOD',
  FINISHED_TAX_PAYMENT: 'FINISHED_TAX_PAYMENT',
  REOPEN_PERIOD: 'REOPEN_PERIOD',
  CALCULATE_TAX: 'CALCULATE_TAX',
} as const;

// 2. Định nghĩa Trạng thái chuẩn chung cho toàn bộ App
export enum LOG_STATUS {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  START = 'START',
}
