// 1. Chỉ định nghĩa Hành động (Không kèm trạng thái)
export const LOG_ACTIONS = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  TAX_SUBMIT: 'TAX_SUBMIT',
  TAX_CLOSE_PERIOD: 'TAX_CLOSE_PERIOD',
  SET_ONBOARDING: 'SETUP_ONBOARDING',
  UPDATE_ONBOARDING: 'UPDATE_ONBOARDING',
  UPLOAD_IMG: 'UPLOAD_IMAGE_TO_CLOUDINARY',
  CREATE_INVOICE: 'CREATE_INVOICE',
  UPDATE_INVOICE: 'UPDATE_INVOICE',
  CANCEL_INVOICE: 'CANCEL_INVOICE',
  CREATE_INBOUND_INVOICE: 'CREATE_INBOUND_INVOICE',
  CANCEL_INBOUND_INVOICE: 'CANCEL_INBOUND_INVOICE',
  SYNC_INVENTORY: 'SYNC_INVENTORY',

  CREATE_VOUCHER_CATEGORY: 'CREATE_VOUCHER_CATEGORY',
  UPDATE_VOUCHER_CATEGORY: 'UPDATE_VOUCHER_CATEGORY',
  DELETE_VOUCHER_CATEGORY: 'DELETE_VOUCHER_CATEGORY',

  CREATE_VOUCHER: 'CREATE_VOUCHER',
  UPDATE_VOUCHER: 'UPDATE_VOUCHER',
  CANCEL_VOUCHER: 'CANCEL_VOUCHER',
} as const;

// 2. Định nghĩa Trạng thái chuẩn chung cho toàn bộ App
export enum LOG_STATUS {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  START = 'START',
}
